- name: Maven Package and Deploy
  hosts: localhost
  connection: local
  tasks:
  # we can also use the 'args' form to provide the options.
- name: shell script execution to run shell commands
  ansible.builtin.shell: myScript.sh
     
      notify:
        - Restart tomcat  
     
- name: wait for tomcat to start
  wait_for: port=8081 timeout=60
    
  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
     
