---
- name: Maven Package and Deploy
  hosts: localhost
  connection: local
  tasks:
   - name: Copy artifct to tomcat server
     copy: src=/home/ansadmin/artifact/*.war dest=/opt/tomcat/tomcat/webapps 
     notify:
       - Restart tomcat  
  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
     
