---
- name: Maven Package and Deploy
  hosts: localhost
  connection: local
  tasks:
- name: script execution to run  commands
  shell: "./myScript.sh"
  notify:
    - Restart tomcat  
     
- name: wait for tomcat to start
  wait_for: port=8081 timeout=60
    
  handlers:
    - name: Restart tomcat
      service: name=tomcat state=restarted
     
